### ISSUE TITLE
why always show:Error: cannot estimate gas; transaction may fail or may require manual gas limit

### ISSUE THREAD

**Issue by fuckgm** [godtoy/bsc-swap-autotrade-bot-v1#6]
when i run dev and i change some config string,i get error:Error: cannot estimate gas; transaction may fail or may require manual gas limit.

**Comment by fuckgm** [comment]
when i use yarn start ,it's show :ERROR in Entry module not found: Error: Can't resolve './src'

**Comment by sleeyax** [comment]
@fuckgm why did you close this isse? Please share the solution.

**Comment by jaybiz007** [comment]
It may be the author who created another account and commented here just to make the project look a bit genuine. Something isn't right about this project.
